openapi: 3.0.0
info:
  title: Book Store API
  version: 1.0.0
  contact:
    email: contact@bookstore.com
paths:
  /books:
    get:
      summary: Get list of books
      operationId: getBooks
      tags:
        - books
      responses:
        '200':
          description: List of books
components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        isbn:
          type: string
