openapi: 3.0.0
info:
  title: Sample Pet Store API
  version: 1.0.0
  contact:
    email: support@petstore.example.com
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A list of pets.
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
