openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: This is a sample API
  contact:
    name: Support
    email: support@example.com
paths:
  /users:
    get:
      summary: Get user list
      description: Returns a list of users.
      tags:
        - users
      responses:
        '200':
          description: A list of users.
tags:
  - name: users
servers:
  - url: https://api.example.com
